version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ../app
    container_name: python_app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432
    volumes:
      - ../app:/app
    ports:
      - "5000:5000"


      